### ISSUE TITLE
[suggestion] Add server option to set who is able to set messages/in-game events for Twitch events

### ISSUE THREAD

**Issue by Fireztonez** [blakdragan7/vscci#4]
I think the server owner should always keep control of who can do what on the server. So I think it would be nice to have a whitelist of people able to configure on is side what will appens for each event in is lives. All other persons VSCCI configuration will not be execute.

By example, if I have my own server and I play with multiple persons, and possibily one or 2 other streamers I know and trust, I would like to be able to say ok; "fireztonez", "alfatossa", "blakdragan7"` can use VSCCI, to send chat notif and in future execute event in-game, like Temporal Storm, spawning mobs, give items, etc.

I think the best would be to keep event configs in client side and not server side, but send to the server for execution when needed, to execute by the server. Like that I can configure something for my channel, and you can configure something different for your channel, event if you played on the same server.

If you can, I think it would be even better to be able to connect to a server with vscci installed, without having that mod installed, unless I want to configure somes actions.

Doing thing like that will keep all private informations on the client side, and just send informations for actions to exectute to the server. I don't think it is needed to have all Twitch Token, StreamLabs Token, StreamElements Token on the server side.

Again, this suggestion came from the Content Creator Integration mod for Minecraft (https://www.curseforge.com/minecraft/mc-mods/content-creator-integration)

**Comment by blakdragan7** [comment]
Interesting ideas. Here are my thoughts on your suggestions:
1.  I like the idea of the server side being able to control and limit who can use vscci makes perfect sense. 
2. With the current design, even with things being server side, everyone can have there own configuration. The difference is the events are created server side and forwarded to the client. But everyone is able to have there own configuration currently. I don't think it's a huge issue storing tokens server side as that's what almost all programs do that interact with twitch do currently. I am also specifically generating the least authorized token, so the most someone could do with it is be notified you received an event during a stream which to me seems harmless. I only mentions the security stuff in the post out of an abundance of caution.
3. I am unsure of if vintage story allows for clients to connect without sharing the same mods the server runs. If they are, then theoretically it should already work fine without having vscci installed because the server will only ever send things to clients that request it. So if it's never requested,they will never receive traffic.

with all that being said it may make sense to move it client side because twitch does limit the number of subscriptions per IP. The only reason I hesitate is because it's quite a bit of work to change that around.

**Comment by blakdragan7** [comment]
baaaah making it client side makes to much sense. I'm going to have to do it. Consider it on the list of things I intend to implement.

**Comment by blakdragan7** [comment]
as of 8f13781e7dc835960b47304ed8bf3601b9c60e46 all twitch interactions are now client side and new version is on the mod db. Next thing on the list is to add the whitelist config because now that's kinda important. After that, I may check out the rest of these ideas but I'm not sure yet.

**Comment by Fireztonez** [comment]
Nice, I will install the new update now and try that!

For what I see, it should be possible to have a mod only on server side, if you allow that in the `modinfo.json`... There have somes line you can have on that file I think question to control if the mod have to be installed on both side or what;

```
"RequiredOnClient": false,
  "RequiredOnServer": true,
```

**Comment by blakdragan7** [comment]
ok. awesome, I will give that a try.

**Comment by blakdragan7** [comment]
So I tried the above and setting RequiredOnClient to false just prevents it from being loaded client side at all.  So if this is possible it must be done some other way.

**Comment by Fireztonez** [comment]
:o I see, that's good to know... Thank's for information.

**Comment by Fireztonez** [comment]
I just test the mod and see the option file in the server root directory. I think, just for keeping clean and respect the established standard, it would be preferable to move this file in `/data/ModConfig/` (That's where most mod config files is for what I seen on server, at least for Linux Server).

I wonder why that folder is hidden on "/data/" folder on server, but that's how it is XD

**Comment by blakdragan7** [comment]
ah, I had no idea. I will change it now so that it;s in the next version release

**Comment by blakdragan7** [comment]
alright done and committed. Next version it will be in there

**Comment by Fireztonez** [comment]
Oki perfect!

**Comment by blakdragan7** [comment]
All of this is done
