### ISSUE TITLE
Crash when on LAN and non-host tried to create a pie on a table

### ISSUE THREAD

**Issue by VallenFrostweaver** [blakdragan7/vscci#7]
Vintage Story version 1.15 Release Candidate 1
VSCCI 0.0.4

Pastebin of crash report: https://pastebin.com/N5DUskwT
Not sure what really caused it but that's what we were doing when it crashed.

**Comment by blakdragan7** [comment]
so, according to that crash report, you received a "channel sub message" right when the "non-host" was making the pie. The message caused the crash, not the pie so that should be fine. It seems twitch sent an emote that was malformed somehow. I get the feeling when your notifications don't work on your other software for subs it's because of this. I will make a bandaid for now and if there is malformed emotes, I will just ignore them.

**Comment by blakdragan7** [comment]
oddly enough, re-watching your vod, there does not seem to be a sub that happened in chat. so maybe this is an issue with twitchlib thinking there is an event when there isn't or the twitch api itself did something dumb. it;s hard to know, either way a bandaid is possible.

**Comment by blakdragan7** [comment]
This hopefully works with a bandaid as of 931d94e26586453bc68e3ee165c7cbebe81ec14c. But I sadly have no real way to test it. I will leave this open until I get vitrifaction that it works.

**Comment by blakdragan7** [comment]
closing because this has not come up again
